name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and run tests
        run: ./gradlew build

      # Upload libraries to workflow artifacts
      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: libraries
          path: digitalassetlinks/build/outputs/aar/*.aar
          if-no-files-found: error
          retention-days: 5

      # Upload javadoc to workflow artifacts
      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: digitalassetlinks-javadoc
          path: |
            digitalassetlinks/build/docs/*
            !digitalassetlinks/build/docs/**/*.zip
          if-no-files-found: error
          retention-days: 1

  # Note: only runs on 'push' events
  publish-to-gh-pages:
    runs-on: ubuntu-latest
    needs: build
    concurrency: publish-to-gh-pages
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Update digitalassetlinks javadoc
        uses: solana-mobile/gha-commit-artifact-to-branch@v1
        with:
          token: ${{ secrets.UPDATE_GITHUB_PAGES_TOKEN }}
          branch: gh-pages
          artifact-name: digitalassetlinks-javadoc
          dest: digitalassetlinks
          commit-message: 'Update digitalassetlinks javadoc'

  # Note: only runs on 'release' events
  upload-to-release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write # needed for uploading files to releases
    if: ${{ github.event_name == 'release' }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: libraries
          path: libraries
      - uses: actions/download-artifact@v3
        with:
          name: digitalassetlinks-javadoc
          path: digitalassetlinks-javadoc
      - name: Compress digitalassetlinks javadoc
        run: tar -cvzf digitalassetlinks-javadoc/digitalassetlinks-javadoc.tgz -C digitalassetlinks-javadoc javadoc
      - name: Upload files to release
        run: gh release -R ${GITHUB_REPOSITORY} upload ${TAG} ${FILES}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
          FILES: |
            libraries/*.aar
            digitalassetlinks-javadoc/digitalassetlinks-javadoc.tgz